# Generated by Django 4.2.1 on 2023-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather_retriever", "0003_alter_weatherdata_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="weatherdata",
            table="weather_data",
        ),
    ]
