# Generated by Django 4.2.1 on 2023-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_retriever", "0004_alter_weatherdata_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation_units",
            field=models.CharField(default="mm", max_length=255),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temperature_units",
            field=models.CharField(default="°C", max_length=255),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed_units",
            field=models.CharField(default="km/h", max_length=255),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="max_temperature",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="min_temperature",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="precipitation_sum",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
